name: Fire-Risk-Assessments
favicon: null
layout_spectrum: 0.10241
typography_spectrum: 0.9421465012710541
title: Fire Risk Assessments on 0207 175 0435 in the United Kingdom www.Fireinspector.co.uk
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#adadad'
    - '#6e6e6e'
    - '#f3282d'
  brandStrength: 0.8894221282098442
  lightness: 0.4937752434052527
  saturation: 0.8125
  rhythmicContrast: 0.8158959681168199
purpose: []
